//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vueling.Application.Services.Unit.Tests {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_Service_Unit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Service_Unit() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vueling.Application.Services.Unit.Tests.Resource_Service_Unit", typeof(Resource_Service_Unit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a britneyblankenship@quotezart.com.
        /// </summary>
        internal static string email1 {
            get {
                return ResourceManager.GetString("email1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a0ece5db-cd14-4f21-812f-966633e7be86.
        /// </summary>
        internal static string id1 {
            get {
                return ResourceManager.GetString("id1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 7b624ed3-00d5-4c1b-9ab8-c265067ef58b.
        /// </summary>
        internal static string idPolicy1 {
            get {
                return ResourceManager.GetString("idPolicy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Britney.
        /// </summary>
        internal static string name1 {
            get {
                return ResourceManager.GetString("name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a admin.
        /// </summary>
        internal static string role1 {
            get {
                return ResourceManager.GetString("role1", resourceCulture);
            }
        }
    }
}
