//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vueling.Infrastructure.Repository {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_Infrastructure_Repository {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Infrastructure_Repository() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vueling.Infrastructure.Repository.Resource.Infrastructure.Repository", typeof(Resource_Infrastructure_Repository).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El argumento o variable de entrada no es correcto.
        /// </summary>
        internal static string ArgumentError {
            get {
                return ResourceManager.GetString("ArgumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede Borrar la tabla..
        /// </summary>
        internal static string CantDeleteMsg {
            get {
                return ResourceManager.GetString("CantDeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de concurrencia en la Base de datos.
        /// </summary>
        internal static string ConcurrencyError {
            get {
                return ResourceManager.GetString("ConcurrencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la validación.
        /// </summary>
        internal static string DbEntityValidationError {
            get {
                return ResourceManager.GetString("DbEntityValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la actualización de la Base de datos.
        /// </summary>
        internal static string DbUpdateError {
            get {
                return ResourceManager.GetString("DbUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra el directorio.
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  || .
        /// </summary>
        internal static string ErrorLogSeparation {
            get {
                return ResourceManager.GetString("ErrorLogSeparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error operacional.
        /// </summary>
        internal static string InvalidOperationError {
            get {
                return ResourceManager.GetString("InvalidOperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de IO.
        /// </summary>
        internal static string IOE {
            get {
                return ResourceManager.GetString("IOE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error general del JSON.
        /// </summary>
        internal static string Json {
            get {
                return ResourceManager.GetString("Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al leer el archivo JSON.
        /// </summary>
        internal static string JsonReader {
            get {
                return ResourceManager.GetString("JsonReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al serializar.
        /// </summary>
        internal static string JsonSerialization {
            get {
                return ResourceManager.GetString("JsonSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al escribir en el JSON.
        /// </summary>
        internal static string JsonWritter {
            get {
                return ResourceManager.GetString("JsonWritter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de soporte.
        /// </summary>
        internal static string NotSuportedError {
            get {
                return ResourceManager.GetString("NotSuportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Objeto o contexto eliminados.
        /// </summary>
        internal static string ObjectDisposedError {
            get {
                return ResourceManager.GetString("ObjectDisposedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a clients.json.
        /// </summary>
        internal static string PathClients {
            get {
                return ResourceManager.GetString("PathClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C:\Users\user\source\Nuevos Respositorios\Vueling - Examen2 con Json\Json\.
        /// </summary>
        internal static string PathForFiles {
            get {
                return ResourceManager.GetString("PathForFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a policies.json.
        /// </summary>
        internal static string PathPolicies {
            get {
                return ResourceManager.GetString("PathPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DELETE FROM Client.
        /// </summary>
        internal static string QueryToDeleteAllRowsInClientTable {
            get {
                return ResourceManager.GetString("QueryToDeleteAllRowsInClientTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DELETE FROM Policy.
        /// </summary>
        internal static string QueryToDeleteAllRowsInPolicyTable {
            get {
                return ResourceManager.GetString("QueryToDeleteAllRowsInPolicyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de permisos.
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de actualización en la Base de datos.
        /// </summary>
        internal static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
    }
}
